from src.hadocs.core.rules import RuleSet


def load_builtin_rulesets() -> list[RuleSet]:
    return [
        RuleSet(
            name="global",
            platforms={"_global"},
            ignore=[
                "button.*",
                "update.*",
                "event.*",
                "image.*",
                "notify.*",
                "conversation.*",
                "stt.*",
                "tts.*",
                "weather.*",
                "zone.*",
                "*create_snapshot*",
                "*_start*",
                "*_stop*",
                "*_restart*",
                "*_reboot*",
                "*_shutdown*",
                "*format_sd_card*",
                "*sync_time*",
                "*last_seen*",
                "*linkquality*",
                "*firmware*",
                "*pre_release*",
                "*latest_version*",
            ],
            diagnostic=[
                "*rssi*",
                "*signal_strength*",
                "*wifi_signal*",
                "*wifi*",
                "*last_boot*",
                "*uptime*",
                "*memory*",
                "*cpu*",
                "*storage*",
                "*battery_state*",
                "*ip_address*",
                "*mac_address*",
                "*ssid*",
                "*bssid*",
            ],
            important=[
                "light.*",
                "switch.*",
                "camera.*",
                "media_player.*",
                "binary_sensor.*motion*",
                "binary_sensor.*door*",
                "binary_sensor.*window*",
                "binary_sensor.*contact*",
                "sensor.*battery*",
            ],
            device_system_words=[
                "home assistant",
                "integration",
                "plugin",
                "hacs",
                "backup",
                "conversation",
                "google ai",
                "openai",
                "forecast",
                "cloud",
                "sun",
                "met.no",
                "spotify",
                "hass.io",
            ],
            device_virtual_words=[
                "group",
                "cast group",
                "speaker group",
                "all units",
                "dashboard",
                "continuously casting",
            ],
        ),
        RuleSet(
            name="mobile_app",
            platforms={"mobile_app"},
            important=[
                "device_tracker.*",
                "sensor.*battery_level*",
            ],
            ignore=[
                "*activity*",
                "*audio*",
                "*bluetooth*",
                "*bssid*",
                "*connection_type*",
                "*geocoded_location*",
                "*last_update_trigger*",
                "*sim*",
                "*ssid*",
                "*storage*",
                "*steps*",
                "*distance*",
                "*floors*",
                "*app_version*",
                "*watch*",
                "*focus*",
                "*orientation*",
                "*brightness*",
                "*volume*",
            ],
            diagnostic=[
                "*battery_state*",
                "*storage*",
                "*memory*",
                "*cpu*",
                "*last_update*",
            ],
            device_virtual_words=["iphone", "ipad", "watch", "wall display"],
        ),
        RuleSet(
            name="ring",
            platforms={"ring"},
            important=["camera.*", "binary_sensor.*motion*", "binary_sensor.*ding*", "sensor.*battery*"],
            ignore=["button.*", "update.*", "*siren*", "*volume*", "*spotlight*", "*rich_notifications*", "*rss*", "*rssi*", "*wifi*", "*firmware*"],
            diagnostic=["*rssi*", "*wifi*", "*signal*", "*last*", "*health*"],
        ),
        RuleSet(
            name="tapo",
            platforms={"tapo", "tapo_control", "tapo_cameras_control"},
            important=["camera.*", "binary_sensor.*motion*", "binary_sensor.*person*", "sensor.*battery*"],
            ignore=["button.*", "update.*", "*sync_time*", "*timezone*", "*siren*", "*speaker*", "*spotlight*", "*rich_notifications*"],
            diagnostic=["*rssi*", "*signal*", "*wifi*", "*firmware*"],
        ),
        RuleSet(
            name="frigate",
            platforms={"frigate"},
            important=["camera.*", "binary_sensor.*motion*", "sensor.*fps*", "sensor.*detect*"],
            ignore=["button.*", "update.*", "*snapshot*", "*restart*", "*latest_version*"],
            diagnostic=["*cpu*", "*memory*", "*process*", "*bandwidth*", "*skipped*"],
        ),
        RuleSet(
            name="wled",
            platforms={"wled"},
            important=["light.*", "switch.*"],
            ignore=["button.*", "update.*", "*playlist*", "*preset*", "*segment*", "*estimated_current*", "*free_heap*", "*uptime*"],
            diagnostic=["*rssi*", "*wifi*", "*ip*", "*mac*", "*uptime*"],
        ),
        RuleSet(
            name="tplink_deco",
            platforms={"tplink_deco"},
            important=["device_tracker.*", "binary_sensor.*online*"],
            ignore=["*upload_speed*", "*download_speed*", "*total_download*", "*total_upload*", "*signal*"],
            diagnostic=["*rssi*", "*signal*", "*speed*"],
        ),
        RuleSet(
            name="proxmox",
            platforms={"proxmoxve", "proxmox"},
            important=["binary_sensor.*status*", "sensor.*status*", "sensor.*uptime*"],
            ignore=["button.*", "*backup*", "*max_*", "*cpu_usage*", "*memory_usage*", "*disk_usage*"],
            diagnostic=["*cpu*", "*memory*", "*disk*", "*uptime*"],
        ),
        RuleSet(
            name="mqtt_zigbee",
            platforms={"mqtt", "zigbee2mqtt"},
            important=["light.*", "switch.*", "sensor.*battery*", "binary_sensor.*motion*", "binary_sensor.*contact*"],
            ignore=["*linkquality*", "*last_seen*", "*update*", "button.*"],
            diagnostic=["*linkquality*", "*rssi*", "*last_seen*"],
        ),
        RuleSet(name="spotify", platforms={"spotify"}, ignore=["*"], device_system_words=["spotify"]),
        RuleSet(name="hacs", platforms={"hacs"}, ignore=["*"], device_system_words=["hacs"]),
        RuleSet(name="cloud", platforms={"cloud"}, ignore=["*"], device_system_words=["cloud"]),
        RuleSet(
            name="google_cast",
            platforms={"cast", "google_translate"},
            important=["media_player.*"],
            ignore=["*group*", "*app_name*"],
            device_virtual_words=["google home", "nest", "cast"],
        ),
    ]
