from pathlib import Path

from src.hadocs.core.incidents import hidden_incident_count, visible_incidents
from src.hadocs.html.components import action_row, esc, health_ring, metric, root_cause_card
from src.hadocs.html.css import dashboard_css


def build_ai_summary(executive, incidents) -> str:
    if not incidents:
        return "Your installation looks healthy. No major root causes were detected."
    main = incidents[0]
    return (
        f"Your installation is currently {executive.status.lower()}. "
        f"The main root cause is {main.root_cause}, affecting {len(main.affected_entities)} entities "
        f"across {len(main.affected_devices)} devices. "
        f"Fixing the top issues could improve the Health Score from {executive.score} to {executive.potential_score}."
    )


def render_dashboard_html(out: Path, project_name: str, model, executive, incidents, raw_incidents, history_comparison, generated_at: str) -> None:
    out.mkdir(parents=True, exist_ok=True)
    visible = visible_incidents(incidents, limit=12)
    hidden = hidden_incident_count(incidents, limit=12)
    summary = build_ai_summary(executive, incidents)
    physical_devices = [d for d in model.devices.values() if d.is_physical]
    virtual_devices = [d for d in model.devices.values() if d.is_virtual]
    system_devices = [d for d in model.devices.values() if d.is_system]
    root_cards = "\n".join(root_cause_card(incident) for incident in visible)
    actions = "\n".join(action_row(action) for action in executive.actions[:12])
    history = "<p class='summary'>No previous scan comparison is available yet.</p>"
    if history_comparison:
        history = f'''<div class="metric-grid">{metric("Health change", f"{history_comparison['health_delta']:+}")}{metric("Problem entity change", f"{history_comparison['problem_entity_delta']:+}")}{metric("Critical action change", f"{history_comparison['critical_delta']:+}")}</div>'''
    html = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><title>{esc(project_name)} - HADocs</title><meta name="viewport" content="width=device-width, initial-scale=1"><style>{dashboard_css()}</style></head><body>
<div class="shell"><aside class="sidebar"><div class="brand"><div class="logo">HA</div><div><h1>HADocs</h1><p>Smart Home Intelligence</p></div></div><nav class="nav"><a href="#dashboard" class="active">Dashboard</a><a href="#root-causes">Root Causes</a><a href="#actions">Actions</a><a href="#installation">Installation</a><a href="#history">History</a><a href="01_root_causes.md">Markdown Root Causes</a><a href="02_incidents.md">Markdown Incidents</a></nav></aside>
<main class="main" id="dashboard"><section class="hero"><div class="card"><span class="status">{esc(executive.status)}</span><h1 class="hero-title">{esc(project_name)}</h1><p class="summary">{esc(summary)}</p><div class="metric-grid">{metric("Potential score", f"{executive.potential_score}/100")}{metric("Repair time", f"{executive.estimated_repair_minutes} min")}{metric("Main root cause", executive.main_cause)}</div></div><div class="card"><div class="health-grid"><div class="ring-wrap">{health_ring(executive.score)}</div><div><h2>Health Score</h2><p class="summary">Based on physical device health, relevant unavailable entities, areas, duplicates and filtered diagnostic noise.</p></div></div></div></section>
<section class="section card" id="installation"><h2>Installation Overview</h2><div class="metric-grid">{metric("Areas", len(model.areas))}{metric("Physical devices", len(physical_devices))}{metric("Virtual devices", len(virtual_devices))}{metric("System devices", len(system_devices))}{metric("Integrations", len(model.integrations))}{metric("Entities", len(model.entities))}</div></section>
<section class="section card"><h2>Intelligence Summary</h2><div class="metric-grid">{metric("Collapsed root causes", len(incidents))}{metric("Raw incidents", len(raw_incidents))}{metric("Hidden lower-priority", hidden)}</div></section>
<section class="section" id="root-causes"><h2>Top Root Causes</h2><input class="search" id="search" placeholder="Search root causes, devices, integrations..."><div class="cards" id="cards">{root_cards}</div></section>
<section class="section card" id="actions"><h2>Recommended Actions</h2><table class="table"><thead><tr><th>Priority</th><th>Action</th><th>Gain</th><th>Time</th><th>Reason</th></tr></thead><tbody>{actions}</tbody></table></section>
<section class="section card" id="history"><h2>History</h2>{history}</section><p class="footer">Generated by HADocs v0.10.0 at {esc(generated_at)}. Local report only. No cloud. No telemetry.</p></main></div>
<script>const search=document.getElementById('search');if(search){{search.addEventListener('input',()=>{{const q=search.value.toLowerCase().trim();document.querySelectorAll('.searchable').forEach(el=>{{const h=(el.dataset.search||el.textContent||'').toLowerCase();el.style.display=!q||h.includes(q)?'':'none';}});}});}}</script></body></html>'''
    (out / "index.html").write_text(html, encoding="utf-8")
