from __future__ import annotations

from pathlib import Path
import base64

DISPLAY = Path("src/hadocs/utils/display.py")
TEST = Path("tests/test_display_utils.py")
DOC = Path("docs/ISSUE_4_STEP1_DISPLAY_UTILS.md")

DISPLAY_TEXT = base64.b64decode("ZnJvbSBfX2Z1dHVyZV9fIGltcG9ydCBhbm5vdGF0aW9ucwoKTk9fQVJFQV9BU1NJR05FRCA9ICJObyBBcmVhIEFzc2lnbmVkIgoKX1VOQVNTSUdORURfQVJFQV9WQUxVRVMgPSB7CiAgICAiIiwKICAgICJfdWRlbl9vbXLDpWRlIiwKICAgICJfdWRlbl9vbXJhYWRlIiwKICAgICJfdWRlbl9vbXLilJzDsWRlIiwKICAgICJfdWRlbl9vbXLilJzDkWRlIiwKICAgICJ1ZGVuIG9tcsOlZGUiLAogICAgInVkZW4gb21yYWFkZSIsCiAgICAidWRlbiBvbXLilJzDsWRlIiwKICAgICJ1ZGVuIG9tcuKUnMORZGUiLAogICAgInVua25vd24iLAogICAgIm5vbmUiLAogICAgIm51bGwiLAp9CgoKZGVmIGlzX3VuYXNzaWduZWRfYXJlYSh2YWx1ZTogb2JqZWN0KSAtPiBib29sOgogICAgIiIiUmV0dXJuIFRydWUgd2hlbiBIb21lIEFzc2lzdGFudCB1c2VzIGFuIGludGVybmFsIHVuYXNzaWduZWQtYXJlYSB2YWx1ZS4iIiIKICAgIHJldHVybiBzdHIodmFsdWUgb3IgIiIpLnN0cmlwKCkubG93ZXIoKSBpbiBfVU5BU1NJR05FRF9BUkVBX1ZBTFVFUwoKCmRlZiBkaXNwbGF5X2FyZWEodmFsdWU6IG9iamVjdCkgLT4gc3RyOgogICAgIiIiRGlzcGxheSBhIHVzZXItZnJpZW5kbHkgYXJlYSBuYW1lIHdpdGhvdXQgY2hhbmdpbmcgaW50ZXJuYWwgSURzIG9yIGZpbGVuYW1lcy4iIiIKICAgIGlmIGlzX3VuYXNzaWduZWRfYXJlYSh2YWx1ZSk6CiAgICAgICAgcmV0dXJuIE5PX0FSRUFfQVNTSUdORUQKICAgIHJldHVybiBzdHIodmFsdWUgb3IgIiIpLnN0cmlwKCkKCgpkZWYgZGlzcGxheV90ZXh0KHZhbHVlOiBvYmplY3QpIC0+IHN0cjoKICAgICIiIlNtYWxsIHNhZmUgZGlzcGxheSBoZWxwZXIgZm9yIG9wdGlvbmFsIHZhbHVlcy4iIiIKICAgIHJldHVybiAiIiBpZiB2YWx1ZSBpcyBOb25lIGVsc2Ugc3RyKHZhbHVlKQo=").decode("utf-8")
TEST_TEXT = base64.b64decode("ZnJvbSBzcmMuaGFkb2NzLnV0aWxzLmRpc3BsYXkgaW1wb3J0IGRpc3BsYXlfYXJlYSwgZGlzcGxheV90ZXh0LCBpc191bmFzc2lnbmVkX2FyZWEKCgpkZWYgdGVzdF9pc191bmFzc2lnbmVkX2FyZWFfZGV0ZWN0c19ob21lX2Fzc2lzdGFudF9pbnRlcm5hbF92YWx1ZXMoKToKICAgIGFzc2VydCBpc191bmFzc2lnbmVkX2FyZWEoIl91ZGVuX29tcsOlZGUiKQogICAgYXNzZXJ0IGlzX3VuYXNzaWduZWRfYXJlYSgiX3VkZW5fb21yYWFkZSIpCiAgICBhc3NlcnQgaXNfdW5hc3NpZ25lZF9hcmVhKCJfdWRlbl9vbXLilJzDkWRlIikKICAgIGFzc2VydCBpc191bmFzc2lnbmVkX2FyZWEoIiIpCiAgICBhc3NlcnQgaXNfdW5hc3NpZ25lZF9hcmVhKE5vbmUpCgoKZGVmIHRlc3RfZGlzcGxheV9hcmVhX3VzZXNfdXNlcl9mcmllbmRseV9sYWJlbCgpOgogICAgYXNzZXJ0IGRpc3BsYXlfYXJlYSgiX3VkZW5fb21yw6VkZSIpID09ICJObyBBcmVhIEFzc2lnbmVkIgogICAgYXNzZXJ0IGRpc3BsYXlfYXJlYSgiX3VkZW5fb21yYWFkZSIpID09ICJObyBBcmVhIEFzc2lnbmVkIgogICAgYXNzZXJ0IGRpc3BsYXlfYXJlYSgiS8O4a2tlbiIpID09ICJLw7hra2VuIgoKCmRlZiB0ZXN0X2Rpc3BsYXlfdGV4dF9oYW5kbGVzX25vbmUoKToKICAgIGFzc2VydCBkaXNwbGF5X3RleHQoTm9uZSkgPT0gIiIKICAgIGFzc2VydCBkaXNwbGF5X3RleHQoImFiYyIpID09ICJhYmMiCg==").decode("utf-8")
DOC_TEXT = base64.b64decode("IyBJc3N1ZSAjNCBTdGVwIDE6IERpc3BsYXkgVXRpbGl0aWVzCgpBZGRzIGEgdGlueSBwcmVzZW50YXRpb24tb25seSBoZWxwZXIgbW9kdWxlOgoKYGBgdGV4dApzcmMvaGFkb2NzL3V0aWxzL2Rpc3BsYXkucHkKYGBgCgpUaGlzIGRvZXMgbm90IGNoYW5nZSBIZWFsdGggRW5naW5lLCBnZW5lcmF0b3IucHksIHNsdWdpZnkoKSwgbW9kZWwgZGF0YSwgZmlsZW5hbWVzLCBHVUkgb3IgRGFzaGJvYXJkLgoKSXQgb25seSBhZGRzIGhlbHBlcnMgdGhhdCBsYXRlciByZXBvcnRzIGNhbiB1c2UgdG8gZGlzcGxheSBIb21lIEFzc2lzdGFudCBpbnRlcm5hbCB1bmFzc2lnbmVkLWFyZWEgdmFsdWVzIGFzOgoKYGBgdGV4dApObyBBcmVhIEFzc2lnbmVkCmBgYAo=").decode("utf-8")


def main() -> None:
    if not Path("src/hadocs").exists():
        raise SystemExit("Run from repository root: C:\\HomeAssistantDocs")

    DISPLAY.parent.mkdir(parents=True, exist_ok=True)
    DISPLAY.write_text(DISPLAY_TEXT, encoding="utf-8")
    TEST.write_text(TEST_TEXT, encoding="utf-8")
    DOC.write_text(DOC_TEXT, encoding="utf-8")

    print("Issue #4 step 1 applied: display utilities only.")
    print("Run: py -3.14 -m pytest")
    print("Commit if green:")
    print("  git add src/hadocs/utils/display.py tests/test_display_utils.py docs/ISSUE_4_STEP1_DISPLAY_UTILS.md tools/apply_issue4_step1_display_utils.py")
    print('  git commit -m "Add display utilities for area labels"')


if __name__ == "__main__":
    main()
