"""Generate deterministic PI1 runtime-foundation documentation."""
from __future__ import annotations

import json
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "integration" / "hask_runtime"
HASK_PI1 = Path(r"D:\HA-Stability-Knowledge\dist\hadocs_pi1")
STAMP = "<!-- GENERATED by tools/build_hask_pi1.py; DO NOT EDIT -->\n"


def write(name: str, text: str) -> None:
    (OUT / name).write_text(STAMP + text.rstrip() + "\n", encoding="utf-8")


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    for name in ("PI1_STARTING_STATE_MANIFEST.json", "PI1_PREFLIGHT_REPORT.md"):
        shutil.copyfile(HASK_PI1 / name, OUT / name)
    write("PRODUCTION_RUNTIME_FOUNDATION.md", """# Production Runtime Foundation

PI1 adds an optional, local-only HASK runtime under `src/hadocs/knowledge/hask_runtime/`. `BundleDiscovery` resolves an explicit path or deterministic local standard paths. `ContractValidator` validates contract structure, compatibility, HADocs minimum version, checksums and references. `RuntimeCache` stores one immutable content-addressed snapshot in process memory. `KnowledgeProvider` exposes the active snapshot. `BundleManager` owns lifecycle and internal diagnostics.

There is deliberately no import or call from normal scan, scoring, Incident, Finding, report or UI code. Consumers must instantiate the manager explicitly. HASK authoritative YAML and Python modules are never read or imported.
""")
    write("RUNTIME_CONFIGURATION.md", """# Runtime Configuration

| Environment variable | Default | Meaning |
|---|---|---|
| `HADOCS_HASK_ENABLED` | `false` | Enables explicit runtime manager startup |
| `HADOCS_HASK_BUNDLE_PATH` | empty | Optional local bundle directory |
| `HADOCS_HASK_STRICT_VALIDATION` | `true` | Enables reference validation |
| `HADOCS_HASK_CACHE_ENABLED` | `true` | Enables process-local immutable snapshot reuse |

When disabled, startup performs no discovery or bundle I/O. When enabled without a valid bundle, the manager reports internal degraded diagnostics and HADocs continues normally. No network discovery or download exists.
""")
    write("BUNDLE_LIFECYCLE.md", """# Bundle Lifecycle

`startup`: disabled → disabled, or enabled → discover/validate/activate. `reload`: validates current content; checksum hits reuse immutable cache, changed checksums create a new snapshot, and failed reload preserves an already active snapshot. `deactivate`: removes the provider snapshot without deleting cache. `shutdown`: deactivates and clears process memory. Missing/invalid bundles yield `degraded`, never an exception into ordinary HADocs operation.

States are `disabled`, `inactive`, `active`, `degraded`, and `shutdown`. Diagnostics expose discovery source/status, bundle version, checksum, compatibility, validation, cache, trust and graceful-degradation reason.
""")
    write("CACHE_ARCHITECTURE.md", """# Cache Architecture

The cache is process-local, read-only and keyed by manifest aggregate artifact SHA-256. Runtime manifests/artifacts are recursively frozen using tuples and mapping proxies. Only the current checksum snapshot is retained. Invalidation is content-addressed; no timestamp is used. The cache writes no file, never mutates source JSON and never treats the HASK bundle directory as runtime storage. Cache disablement forces validation and reconstruction on every reload.
""")
    write("TRUST_FOUNDATION.md", """# Trust Foundation

PI1 validates required manifest fields, contract major, minimum HADocs version, required artifact set, typed artifact envelopes, per-file SHA-256, aggregate SHA-256 and canonical references. `TrustVerifier` is an injectable protocol; the current `UnsignedChecksumTrust` reports checksum-valid/signature-not-implemented. Checksums establish integrity relative to the manifest, not publisher authenticity.

Future distribution design: publish an immutable bundle plus signed manifest as a release artifact; install offline into a versioned local directory; verify signature against a pinned trust root before atomic activation; retain the previous validated version for rollback; define stable/beta channels, stale policy and explicit update approval. PI1 implements none of the download, channel, signature or automatic-update behavior.
""")
    write("PI1_RUNTIME_FOUNDATION_FINAL_REPORT.md", """# PI1 Runtime Integration Foundation Final Report

## Outcome

Runtime discovery, lifecycle, immutable cache, contract/checksum/version validation, trust extension point and internal diagnostics are implemented without normal-scan integration. HASK remains disabled by default.

## Preservation

The 26 approved dirty-baseline files and 32 completed-pilot files were frozen before PI1. Starting regression was 232 passed. PI1 uses new isolated modules and does not change scoring, Health Score, Findings, Incidents, reports, UI or recovery.

## Tests

Nineteen PI1-specific tests cover startup, shutdown, reload, missing/invalid/corrupt/incompatible bundles, schema/version/checksum failures, cache behavior, immutable snapshots, graceful degradation and read-only source integrity. Final regression: 251 passed. Clean-copy regression: 251 passed. Documentation double-build differences: zero. HASK validators passed and HASK pytest remained 68 passed. Approved-baseline mismatches: zero; unexpected completed-pilot mismatches: zero. Three pilot documentation files received additive PI1 status/ADR sections.

## Remaining work

PI2 requires a separate authorization for normal-scan canonical evidence and candidate pipelines. Release signing, download/update channels, rollback installer, reports/API/UI, confirmation policy and scoring remain out of scope.
""")
    print("Built PI1 runtime-foundation documentation")
