"""Build deterministic isolated HASK pilot reports and traces."""
from __future__ import annotations

from dataclasses import asdict
import json
from pathlib import Path
import shutil
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from hadocs.knowledge.hask_pilot import PilotConfig, run_pilot  # noqa: E402

HASK = Path(r"D:\HA-Stability-Knowledge")
BUNDLE = HASK / "dist" / "hadocs"
OUT = ROOT / "docs" / "integration" / "hask_pilot"
FIXTURES = ROOT / "tests" / "fixtures" / "hask_pilot"
STAMP = "<!-- GENERATED by tools/build_hask_pilot.py; DO NOT EDIT -->\n"


def write_json(name: str, value: object) -> None:
    (OUT / name).write_text(json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n", encoding="utf-8")


def write_md(name: str, value: str) -> None:
    (OUT / name).write_text(STAMP + value.rstrip() + "\n", encoding="utf-8")


def trace(platform: str, result: dict) -> str:
    canonical = [item for match in result["canonical_evidence"] for item in match["canonical_ids"]]
    candidates = result["candidates"]
    return f"""# HADocs {platform.title()} Pilot Trace

- Input observations: {', '.join(item['evidence_id'] for item in result['local_evidence'])}
- Local HADocs evidence: preserved verbatim in `local_evidence`
- Canonical evidence: {', '.join(canonical) or 'no_match'}
- Matched scenarios: {', '.join(sorted({item for candidate in candidates for item in candidate['scenarios']}))}
- Candidate root causes: {', '.join(item['candidate_id'] for item in candidates)}
- Competing causes: {', '.join(sorted({item for candidate in candidates for item in candidate['competing_causes']}))}
- Supporting evidence: {', '.join(sorted({item for candidate in candidates for item in candidate['supporting_canonical_evidence']}))}
- Contradicting evidence: none supplied by local pilot fixture
- Missing evidence: {', '.join(sorted({item for candidate in candidates for item in candidate['missing_evidence']}))}
- Recommendations: {', '.join(sorted({item for candidate in candidates for item in candidate['recommendations']}))}
- Verification: {', '.join(sorted({item for candidate in candidates for item in candidate['verification']}))}
- Provenance: {', '.join(sorted({item for candidate in candidates for item in candidate['provenance']}))}
- Conflicts preserved: {sum(len(item['conflicts']) for item in candidates)}
- Known gaps preserved: {sum(len(item['known_gaps']) for item in candidates)}
- Final pilot status: `{result['status']}`
- Confirmed candidates: none
- Health Score impact: none
"""


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    config = PilotConfig(True, BUNDLE, True)
    results = {}
    for platform in ("unifi", "mikrotik"):
        local = json.loads((FIXTURES / f"{platform}_local_evidence.json").read_text(encoding="utf-8"))
        results[platform] = run_pilot(platform, local, config)
        write_json(f"HADOCS_{platform.upper()}_PILOT_RESULT.json", results[platform])
        write_md(f"HADOCS_{platform.upper()}_PILOT_TRACE.md", trace(platform, results[platform]))

    baseline = HASK / "dist" / "hadocs_pilot"
    for name in ("HADOCS_APPROVED_DIRTY_BASELINE.json", "HADOCS_APPROVED_DIRTY_BASELINE.md", "HADOCS_APPROVED_DIRTY_BASELINE.patch", "HADOCS_DIRTY_BASELINE_CLASSIFICATION.md"):
        shutil.copyfile(baseline / name, OUT / name)

    write_md("HADOCS_BASELINE_TEST_REPORT.md", """# HADocs Baseline Test Report

The approved dirty baseline was tested before pilot code was added. System `python` was 3.9.13 and below the declared `>=3.11` requirement. The HASK virtual environment collected the suite but lacked HADocs' declared `requests` dependency: 204 passed and 12 failed for that environment reason. The installed Python 3.14.3 runtime had pytest 9.1.1, requests 2.34.2 and PyYAML 6.0.3; with explicit `PYTHONPATH=src;.` and an isolated temp directory, all 216 baseline tests passed in 0.45 seconds.

Existing baseline risks: `pyproject.toml` declares `pythonpath = ["scr"]`, and the configured `.pytest_tmp` path was inaccessible. Neither was modified by the pilot.
""")
    write_md("HADOCS_INTEGRATION_PILOT_PREFLIGHT.md", """# HADocs Integration Pilot Preflight

HASK is a local non-Git provider workspace. Contract 1.0.0 contains a valid manifest, 13 checksum-bound artifacts, a JSON-only reference consumer, 14 compatibility fixtures and complete UniFi/MikroTik fixtures. HADocs is the approved dirty baseline on branch `main`, commit `590cc33a9762c4d22699f20c60d136ef2c4de00c`, frozen as 5 tracked modifications plus 21 untracked files. No merge conflicts were present and all 216 baseline tests passed under Python 3.14.3.

The explicit runtime source `src/hadocs/version.py` identifies the public desktop runtime as `0.15.0-rc1`. Package metadata remains `0.11.1` and the knowledge exporter defaults to `0.12.0`; this pre-existing version divergence is recorded rather than normalized by the pilot.
""")
    write_md("HADOCS_EVIDENCE_MODEL_REPORT.md", """# HADocs Evidence Model Report

| Path | Interface | Fields and lifecycle | Compatibility |
|---|---|---|---|
| `src/hadocs/core/incidents_v2.py` | `EntityEvidence` | required entity, interpretation and freshness; collected per entity | Local observation layer; no provenance/conflict fields |
| `src/hadocs/core/incidents_v2.py` | `DeviceEvidence` | required device/reachability; optional fault, transient, expected and stale groups | Aggregated evidence; not replaced by HASK |
| `src/hadocs/domain/findings.py` | `Finding` | code/category/severity/target/message/penalty required; confidence and metadata optional | `metadata` could preserve HASK data, but pilot avoids production findings |
| `src/hadocs/core/state_interpreter.py` | `StateInterpretation` | meaning, confidence and explanation derived from local state | Local evidence remains authoritative for runtime state |

Callers are `build_incidents_v2`, integration health, policy/scoring and tests. There is no single canonical Evidence persistence contract. The pilot therefore accepts explicit local evidence DTOs and preserves them beside derived canonical matches.
""")
    write_md("HADOCS_ROOT_CAUSE_MODEL_REPORT.md", """# HADocs Root Cause Model Report

`src/hadocs/core/incidents_v2.py::IncidentV2` is the active root-cause/report DTO: incident ID, title, category, severity, root cause and confidence are required; affected entity/device/integration lists, evidence and recommendation are optional; score gain, repair minutes and children are compatibility fields. Builders create device and integration incidents, collapse logic groups them, advisor/report/UI code consumes them.

HASK candidates cannot be mapped losslessly because `IncidentV2` has no applicability, canonical provenance, conflicts, missing evidence, verification status or candidate/confirmation distinction. The pilot uses `KnowledgeCandidate` metadata and creates no `IncidentV2`. HADocs retains confirmation, grouping, severity, priority and scoring ownership.
""")
    write_md("HADOCS_REPORT_INTERFACE_REPORT.md", """# HADocs Report Interface Report

`src/hadocs/knowledge/exporter.py` serializes health, incidents and recommendations to JSON/Markdown; `src/hadocs/reports/generator.py`, `src/hadocs/html/` and `src/hadocs/web/` consume report DTOs. Existing payloads expose root cause, severity, evidence strings, affected objects and recommendations, but not full HASK provenance/conflicts/applicability. Pilot results therefore remain isolated JSON/Markdown under `docs/integration/hask_pilot/` and do not alter production report or API payloads.
""")
    write_md("HADOCS_HEALTH_SCORE_INTERFACE_REPORT.md", """# HADocs Health Score Interface Report

`src/hadocs/intelligence/health_score_v2.py::HealthScoreV2.calculate` consumes unsuppressed `Finding` objects. Deduction uses finding penalty × confidence × severity multiplier with diminishing repetition, then category weights. `HealthScoreResult` contains score, potential score, grade, category results and top causes. The pilot creates no Findings, invokes no scorer and exports `health_score_impact: null`; therefore existing scoring semantics are unchanged.
""")
    write_md("HASK_HADOCS_FIELD_MAPPING_MATRIX.md", """# HASK–HADocs Field Mapping Matrix

| HASK field | HADocs target | Mapping | Lossless | Adapter logic | Status |
|---|---|---|---|---|---|
| platform | pilot platform ID | direct | yes | index lookup | direct |
| observation | `LocalEvidence` + canonical match | adapted | yes | preserve local input | adapted |
| canonical/supporting evidence | `CanonicalEvidenceMatch` | adapted | yes | bounded mapping table | adapted |
| contradicting/missing evidence | `KnowledgeCandidate` | adapted | yes | explicit tuples | adapted |
| root-cause candidate | `KnowledgeCandidate` | adapted | yes | never create confirmed IncidentV2 | adapted |
| competing cause | candidate metadata | direct | yes | canonical IDs | direct |
| scenario | candidate metadata | direct | yes | scenario IDs | direct |
| recommendation/verification | candidate metadata | direct | yes | canonical IDs | direct |
| applicability/provenance/conflict/gap | candidate metadata | adapted | yes | retain full JSON objects/IDs | adapted |
| confidence input | default knowledge weight | adapted | yes | never feed production confidence | adapted |
| readiness | bundle platform metadata | direct | yes | read only | direct |
| contract version | loader negotiation | direct | yes | SemVer major gate | direct |
| severity/priority/confirmation/Health Score | HADocs-owned | none | n/a | outside pilot | not_applicable |
""")
    write_md("HASK_HADOCS_ADAPTER_ARCHITECTURE.md", """# HASK–HADocs Adapter Architecture

The adapter is isolated under `src/hadocs/knowledge/hask_pilot/`. `PilotConfig` is disabled by default; `loader` reads local JSON, negotiates version, validates required typed structure, checks per-file/aggregate SHA-256 and resolves references; `adapters` maps only bounded UniFi/MikroTik evidence and constructs candidate-only metadata; `runner` is explicit and has no normal-scan hook.

It imports no HASK modules, reads no YAML, downloads nothing, writes no cache, mutates no bundle and is not a singleton. Missing configuration is harmless while disabled and controlled when enabled.
""")
    write_md("HADOCS_HASK_SCORING_BOUNDARY_REPORT.md", """# HADocs HASK Scoring Boundary Report

HADocs production score inputs are Findings with penalty, confidence, severity, category and suppression. HASK supporting, contradicting and missing evidence, applicability conflicts and partial verification have no established production conversion. Any conversion would change scoring semantics. The pilot therefore reports dry-run inputs only: knowledge weight remains metadata, missing/unknown/conflict never become negative evidence, partial verification never confirms, and no Finding or score delta is produced.
""")
    write_md("HASK_HADOCS_DISTRIBUTION_TRUST_PREFLIGHT.md", """# HASK–HADocs Distribution and Trust Preflight

The pilot uses an explicit local installation path and verifies manifest plus artifact SHA-256 offline. Production options are an embedded release artifact or separately installed local bundle; network download is excluded from the pilot. A future release needs a signed release manifest, defined trust root, atomic installation, retained previous bundle for rollback, stale-content policy, supported-version window and offline fallback. SHA-256 proves integrity against the manifest, not publisher authenticity. No signing is implemented here.
""")
    write_md("HASK_HADOCS_ISOLATED_INTEGRATION_PILOT_FINAL_REPORT.md", f"""# HASK × HADocs Isolated Integration Pilot Final Report

## Executive Summary

The isolated adapter loads HASK contract 1.0.0 read-only and maps UniFi/MikroTik pilot evidence into candidate-only metadata without replacing HADocs Evidence, IncidentV2, scoring, reports or UI.

## Approved Baseline

Branch `main`, commit `590cc33a9762c4d22699f20c60d136ef2c4de00c`, plus 5 tracked and 21 untracked files was frozen by checksum and patch. Baseline tests: 216 passed. Existing HUDD work was preserved and not modified.

## Pilot Changes

New isolated config, loader, models, adapters, runner, fixtures, tests, generator and reports were added. There is no production scan hook. Feature default is disabled.

## Results

UniFi: `{results['unifi']['status']}`. MikroTik: `{results['mikrotik']['status']}`. Provenance, missing evidence, applicability, conflicts/gaps and verification remain in candidate metadata. Confirmed candidates: zero. Health Score impact: none.

## Failure tests and regression status

Sixteen pilot tests cover disabled mode, missing path, manifest/version/checksum/file/reference failures, additive fields, unknown/no-match/unavailable semantics, conflicts, partial verification, deduplication, read-only access and both vertical slices. Baseline: 216 passed. Final and clean-copy regression: 232 passed. Pilot report double-build SHA-256 differences: zero. All 26 approved baseline file checksums remained unchanged.

## Version compatibility

HADocs runtime `0.15.0-rc1` (manifest SemVer base `0.15.0`), Python 3.14.3, branch `main`, commit above, tested 2026-07-24. Package metadata `0.11.1` and exporter default `0.12.0` remain documented baseline divergences. Contract major 1 is supported by the pilot.

## Production readiness

The pilot proves the adapter boundary, not production readiness. Permanent installation/update, signature trust, normal-scan evidence mapping, report/API/UI exposure and score policy require a separately approved Production Integration Phase 1. Existing version-marker divergence (`0.11.1`, `0.12.0`, `0.15.0-rc1`) and pytest configuration drift remain baseline maintenance risks.
""")
    print(f"Built isolated HASK pilot reports for {', '.join(results)}")
