"""Default-disabled HASK database infrastructure and frozen physical schema."""

from .config import (
    HaskDatabaseApplicationConfig,
    HaskDatabaseConfig,
    HaskDatabaseIdentityConfig,
    canonical_installation_uuid,
    derive_installation_scope,
)
from .connection import HaskSQLiteConnectionFactory, ManagedSQLiteConnection
from .errors import (
    FeatureDisabledError,
    HaskDatabaseError,
    IntegrityValidationError,
    MigrationValidationError,
    PragmaValidationError,
    SecretUnavailableError,
    RepositoryError, NotFoundError, AlreadyExistsError, ConstraintViolationError,
    ValidationFailureError, ConcurrencyConflictError, StorageFailureError,
    CorruptionDetectedError, RepositoryMigrationFailureError,
    RepositorySecretUnavailableError, BundleMismatchError, VersionIncompatibleError,
    IdempotencyConflictError, NestedTransactionError, RecoveryModeError,
)
from .integrity import IntegrityResult, SQLiteIntegrityValidator
from .migrations import (
    Migration,
    MigrationRegistry,
    MigrationRunner,
    SchemaVersionStore,
)
from .migration_chain import (
    BATCH2_MIGRATIONS,
    BATCH2_REGISTRY,
    PragmaSchemaVersionStore,
    initialize_batch2_schema,
)
from .schema import SchemaConformance, inspect_schema, schema_sha256, verify_schema
from .secrets import (
    CredentialStoreBackend,
    CredentialStoreSecretProvider,
    LinuxContainerSecretProviderPlaceholder,
    NullSecretProvider,
    POSIX_FILE_CREDENTIAL_BACKEND,
    PosixFileCredentialBackend,
    ProtectedSecretBackend,
    SecretDescriptor,
    SecretProvider,
    SecretReference,
    SecretState,
    WINDOWS_CREDENTIAL_BACKEND,
    resolve_posix_credential_location,
    select_secret_provider,
)
from .service import (
    CapabilityOutcomeInput,
    EntityPersistenceInput,
    EntityPersistenceRecords,
    EntityPersistenceRequest,
    EntityPersistenceResult,
    HaskDatabaseService,
    ObservationInput,
    OperationalReplayResult,
    OperationalReplayState,
    OperationalSliceRecords,
    OperationalSliceRequest,
    OperationalSliceResult,
    PersistedEntityRecords,
    PersistedEntityResult,
    PersistedRelationshipRecords,
    PersistedRelationshipResult,
    RelationshipPersistenceInput,
    RelationshipPersistenceRecords,
    RelationshipPersistenceRequest,
    RelationshipPersistenceResult,
    ScanCompletionRecords,
    ScanCompletionIntent,
    ScanCompletionRequest,
    ScanCompletionResult,
    ServiceState,
    ServiceStatus,
)
from .repository_contracts import (
    FROZEN_OWNERSHIP, RepositoryContract, RepositoryDescriptor, RepositoryOwner,
    validate_frozen_ownership,
)
from .repositories import (
    AuditRepository, BaseRepository, CollisionRegistryRepository,
    CompatibilityDecisionRepository, EntityRepository, LogicalInstallationRepository,
    MigrationStateRepository, ObservationRepository, RelationshipRepository,
    RepositoryFactory, RepositoryRegistry, ScanRunRepository, VersionStateRepository,
    default_repository_registry,
)
from .coordination import (
    IdempotencyCoordinator, RecoveryCoordinator, RecoveryState, canonical_intent_digest,
)
from .transactions import RetryPolicy, SerializedTransactionManager, UnitOfWork, translate_sqlite_error
from .uow_contracts import (
    ENTITY_PERSISTENCE_CONTRACT,
    RELATIONSHIP_PERSISTENCE_CONTRACT,
    SCAN_COMPLETION_CONTRACT,
    UnitOfWorkContract,
)
from .validators import (
    ENTITY_PRESENT_REASON,
    ENTITY_RECREATION_REASON,
    ENTITY_REMOVAL_REASON,
    RELATIONSHIP_PRESENT_REASON,
    RELATIONSHIP_RECREATION_REASON,
    RELATIONSHIP_REMOVAL_REASON,
    SCAN_AUDIT_EVIDENCE_ROLE,
    SCAN_AUDIT_SUBJECT_ROLE,
    validate_capability_intent,
    validate_completion_intent,
    validate_entity_intent,
    validate_entity_transition,
    validate_observation_ownership,
    validate_relationship_intent,
    validate_relationship_transition,
    validate_scan_state,
)

__all__ = [
    "FeatureDisabledError",
    "BATCH2_MIGRATIONS",
    "BATCH2_REGISTRY",
    "HaskDatabaseConfig",
    "HaskDatabaseApplicationConfig",
    "HaskDatabaseIdentityConfig",
    "HaskDatabaseError",
    "HaskDatabaseService",
    "HaskSQLiteConnectionFactory",
    "IntegrityResult",
    "IntegrityValidationError",
    "LinuxContainerSecretProviderPlaceholder",
    "CredentialStoreBackend",
    "CredentialStoreSecretProvider",
    "PosixFileCredentialBackend",
    "POSIX_FILE_CREDENTIAL_BACKEND",
    "WINDOWS_CREDENTIAL_BACKEND",
    "resolve_posix_credential_location",
    "select_secret_provider",
    "ManagedSQLiteConnection",
    "Migration",
    "MigrationRegistry",
    "MigrationRunner",
    "MigrationValidationError",
    "NullSecretProvider",
    "ProtectedSecretBackend",
    "PragmaValidationError",
    "PragmaSchemaVersionStore",
    "SQLiteIntegrityValidator",
    "SchemaVersionStore",
    "SchemaConformance",
    "SecretDescriptor",
    "SecretProvider",
    "SecretReference",
    "SecretState",
    "SecretUnavailableError",
    "ServiceState",
    "ServiceStatus",
    "ObservationInput",
    "EntityPersistenceInput",
    "EntityPersistenceRecords",
    "EntityPersistenceRequest",
    "EntityPersistenceResult",
    "PersistedEntityRecords",
    "PersistedEntityResult",
    "RelationshipPersistenceInput",
    "RelationshipPersistenceRecords",
    "RelationshipPersistenceRequest",
    "RelationshipPersistenceResult",
    "PersistedRelationshipRecords",
    "PersistedRelationshipResult",
    "OperationalReplayResult",
    "OperationalReplayState",
    "CapabilityOutcomeInput",
    "OperationalSliceRecords",
    "OperationalSliceRequest",
    "OperationalSliceResult",
    "ScanCompletionRecords",
    "ScanCompletionIntent",
    "ScanCompletionRequest",
    "ScanCompletionResult",
    "initialize_batch2_schema",
    "inspect_schema",
    "schema_sha256",
    "verify_schema",
    "canonical_installation_uuid",
    "derive_installation_scope",
    "RepositoryError", "NotFoundError", "AlreadyExistsError",
    "ConstraintViolationError", "ValidationFailureError", "ConcurrencyConflictError",
    "StorageFailureError", "CorruptionDetectedError", "RepositoryMigrationFailureError",
    "RepositorySecretUnavailableError", "BundleMismatchError", "VersionIncompatibleError",
    "IdempotencyConflictError", "NestedTransactionError", "RecoveryModeError",
    "FROZEN_OWNERSHIP", "RepositoryContract", "RepositoryDescriptor", "RepositoryOwner",
    "validate_frozen_ownership", "BaseRepository", "LogicalInstallationRepository",
    "CollisionRegistryRepository", "EntityRepository", "RelationshipRepository",
    "ScanRunRepository", "ObservationRepository", "CompatibilityDecisionRepository",
    "AuditRepository", "VersionStateRepository", "MigrationStateRepository",
    "RepositoryFactory", "RepositoryRegistry", "default_repository_registry",
    "IdempotencyCoordinator", "RecoveryCoordinator", "RecoveryState",
    "canonical_intent_digest", "RetryPolicy", "SerializedTransactionManager",
    "UnitOfWork", "translate_sqlite_error",
    "UnitOfWorkContract", "SCAN_COMPLETION_CONTRACT", "ENTITY_PERSISTENCE_CONTRACT",
    "RELATIONSHIP_PERSISTENCE_CONTRACT",
    "ENTITY_PRESENT_REASON", "ENTITY_RECREATION_REASON", "ENTITY_REMOVAL_REASON",
    "RELATIONSHIP_PRESENT_REASON", "RELATIONSHIP_RECREATION_REASON",
    "RELATIONSHIP_REMOVAL_REASON",
    "SCAN_AUDIT_EVIDENCE_ROLE", "SCAN_AUDIT_SUBJECT_ROLE",
    "validate_capability_intent", "validate_completion_intent",
    "validate_entity_intent", "validate_entity_transition",
    "validate_relationship_intent", "validate_relationship_transition",
    "validate_observation_ownership", "validate_scan_state",
]
