name: Home Assistant Add-on

on:
  push:
    branches:
      - main
    paths:
      - "hadocs/**"
      - ".github/workflows/addon.yml"

  pull_request:
    paths:
      - "hadocs/**"
      - ".github/workflows/addon.yml"

jobs:
  addon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Add-on
        run: docker build --pull -f hadocs/Dockerfile -t hadocs-addon ./hadocs